[tool.black]
# Default black line length limit
line-length = 88
# Target python2.7 and python3.*
target-version = ['py27', 'py35', 'py36', 'py37', 'py38']

[tool.isort]
# Enable isort black compatibility flags
profile = "black"
multi_line_output = 3
